# govechoOS — конфигурация live-системы (live-boot / live-config)
# Автор: ZHBR-228 | Лицензия: MIT
LIVE_HOSTNAME="govechoos"
LIVE_USERNAME="govecho"
LIVE_USER_FULLNAME="govechoOS Live User"
LIVE_CONFIG_Locale="ru_RU.UTF-8"
LIVE_CONFIG_TIMEZONE="Europe/Moscow"
